apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker-container
          image: celery-worker-fastapi:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis-service:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis-service:6379/0
